export {}
// generated by typed-config.js
declare module "atom" {
  interface ConfigValues {
    "pulsar-typescript.unusedAsInfo": boolean
    "pulsar-typescript.checkAllFilesOnSave": boolean
    "pulsar-typescript.autocompletionSuggestionPriority": number
    "pulsar-typescript.autocompletionInclusionPriority": number
    "pulsar-typescript.autocompletionExcludeLowerPriority": boolean
    "pulsar-typescript.autocompletionUseFuzzyFilter": boolean
    "pulsar-typescript.autocompletionStrictFilterIgnoreCase": boolean
    "pulsar-typescript.autocompletionStrictFilterLongestMatchFirst": boolean
    "pulsar-typescript.locale": string
    "pulsar-typescript.buildStatusTimeout": number
    "pulsar-typescript.getErrDebounceTimeout": number
    "pulsar-typescript.showSemanticView": boolean
    "pulsar-typescript.autocompleteParens": boolean
    "pulsar-typescript.includeCompletionsForModuleExports": boolean
    "pulsar-typescript.quotePreference": "auto" | "double" | "single"
    "pulsar-typescript.importModuleSpecifierEnding": "auto" | "minimal" | "index" | "js"
    "pulsar-typescript.importModuleSpecifierPreference":
      | "auto"
      | "relative"
      | "non-relative"
      | "shortest"
      | "project-relative"
    "pulsar-typescript.tsdkPath": string
    "pulsar-typescript.ignoredDiagnosticCodes": string[]
    "pulsar-typescript.ignoreUnusedSuggestionDiagnostics": boolean
    "pulsar-typescript.ignoreNonSuggestionSuggestionDiagnostics": boolean
    "pulsar-typescript.ignoredSuggestionDiagnostics": string[]
    "pulsar-typescript.suppressAllDiagnostics": boolean
    "pulsar-typescript.tsFileExtensions": string[]
    "pulsar-typescript.jsFileExtensions": string[]
    "pulsar-typescript.extensionsFromGrammars": boolean
    "pulsar-typescript.tsSyntaxScopes": string[]
    "pulsar-typescript.jsSyntaxScopes": string[]
    "pulsar-typescript.tsserverInstancePerTsconfig": boolean
    "pulsar-typescript.longLineLength": number
    "pulsar-typescript.largeFileLineCount": number
    "pulsar-typescript.largeFileNoFollowCursor": boolean
    "pulsar-typescript": {
      unusedAsInfo: boolean
      checkAllFilesOnSave: boolean
      autocompletionSuggestionPriority: number
      autocompletionInclusionPriority: number
      autocompletionExcludeLowerPriority: boolean
      autocompletionUseFuzzyFilter: boolean
      autocompletionStrictFilterIgnoreCase: boolean
      autocompletionStrictFilterLongestMatchFirst: boolean
      locale: string
      buildStatusTimeout: number
      getErrDebounceTimeout: number
      showSemanticView: boolean
      autocompleteParens: boolean
      includeCompletionsForModuleExports: boolean
      quotePreference: "auto" | "double" | "single"
      importModuleSpecifierEnding: "auto" | "minimal" | "index" | "js"
      importModuleSpecifierPreference:
        | "auto"
        | "relative"
        | "non-relative"
        | "shortest"
        | "project-relative"
      tsdkPath: string
      ignoredDiagnosticCodes: string[]
      ignoreUnusedSuggestionDiagnostics: boolean
      ignoreNonSuggestionSuggestionDiagnostics: boolean
      ignoredSuggestionDiagnostics: string[]
      suppressAllDiagnostics: boolean
      tsFileExtensions: string[]
      jsFileExtensions: string[]
      extensionsFromGrammars: boolean
      tsSyntaxScopes: string[]
      jsSyntaxScopes: string[]
      tsserverInstancePerTsconfig: boolean
      longLineLength: number
      largeFileLineCount: number
      largeFileNoFollowCursor: boolean
    }
  }
}
