export {}
// generated by typed-config.js
declare module "atom" {
  interface ConfigValues {
    "pulsar-typescript-updated.unusedAsInfo": boolean
    "pulsar-typescript-updated.checkAllFilesOnSave": boolean
    "pulsar-typescript-updated.autocompletionSuggestionPriority": number
    "pulsar-typescript-updated.autocompletionInclusionPriority": number
    "pulsar-typescript-updated.autocompletionExcludeLowerPriority": boolean
    "pulsar-typescript-updated.autocompletionUseFuzzyFilter": boolean
    "pulsar-typescript-updated.autocompletionStrictFilterIgnoreCase": boolean
    "pulsar-typescript-updated.autocompletionStrictFilterLongestMatchFirst": boolean
    "pulsar-typescript-updated.locale": string
    "pulsar-typescript-updated.buildStatusTimeout": number
    "pulsar-typescript-updated.getErrDebounceTimeout": number
    "pulsar-typescript-updated.showSemanticView": boolean
    "pulsar-typescript-updated.autocompleteParens": boolean
    "pulsar-typescript-updated.includeCompletionsForModuleExports": boolean
    "pulsar-typescript-updated.quotePreference": "auto" | "double" | "single"
    "pulsar-typescript-updated.importModuleSpecifierEnding": "auto" | "minimal" | "index" | "js"
    "pulsar-typescript-updated.importModuleSpecifierPreference":
      | "auto"
      | "relative"
      | "non-relative"
      | "shortest"
      | "project-relative"
    "pulsar-typescript-updated.tsdkPath": string
    "pulsar-typescript-updated.ignoredDiagnosticCodes": string[]
    "pulsar-typescript-updated.ignoreUnusedSuggestionDiagnostics": boolean
    "pulsar-typescript-updated.ignoreNonSuggestionSuggestionDiagnostics": boolean
    "pulsar-typescript-updated.ignoredSuggestionDiagnostics": string[]
    "pulsar-typescript-updated.suppressAllDiagnostics": boolean
    "pulsar-typescript-updated.tsFileExtensions": string[]
    "pulsar-typescript-updated.jsFileExtensions": string[]
    "pulsar-typescript-updated.extensionsFromGrammars": boolean
    "pulsar-typescript-updated.tsSyntaxScopes": string[]
    "pulsar-typescript-updated.jsSyntaxScopes": string[]
    "pulsar-typescript-updated.tsserverInstancePerTsconfig": boolean
    "pulsar-typescript-updated.longLineLength": number
    "pulsar-typescript-updated.largeFileLineCount": number
    "pulsar-typescript-updated.largeFileNoFollowCursor": boolean
    "pulsar-typescript-updated": {
      unusedAsInfo: boolean
      checkAllFilesOnSave: boolean
      autocompletionSuggestionPriority: number
      autocompletionInclusionPriority: number
      autocompletionExcludeLowerPriority: boolean
      autocompletionUseFuzzyFilter: boolean
      autocompletionStrictFilterIgnoreCase: boolean
      autocompletionStrictFilterLongestMatchFirst: boolean
      locale: string
      buildStatusTimeout: number
      getErrDebounceTimeout: number
      showSemanticView: boolean
      autocompleteParens: boolean
      includeCompletionsForModuleExports: boolean
      quotePreference: "auto" | "double" | "single"
      importModuleSpecifierEnding: "auto" | "minimal" | "index" | "js"
      importModuleSpecifierPreference:
        | "auto"
        | "relative"
        | "non-relative"
        | "shortest"
        | "project-relative"
      tsdkPath: string
      ignoredDiagnosticCodes: string[]
      ignoreUnusedSuggestionDiagnostics: boolean
      ignoreNonSuggestionSuggestionDiagnostics: boolean
      ignoredSuggestionDiagnostics: string[]
      suppressAllDiagnostics: boolean
      tsFileExtensions: string[]
      jsFileExtensions: string[]
      extensionsFromGrammars: boolean
      tsSyntaxScopes: string[]
      jsSyntaxScopes: string[]
      tsserverInstancePerTsconfig: boolean
      longLineLength: number
      largeFileLineCount: number
      largeFileNoFollowCursor: boolean
    }
  }
}
